@extends('admin.dash')

@section('admin')

<style>

.form-section {
    margin-bottom: 20px;
}
.remove-section {
    margin-left: 10px;
    background-color: red;
    color: white;
    border: none;
    padding: 5px 10px;
    cursor: pointer;
    border-radius: 3px;
    display: none; 
}
</style>

<div class="page-content">
    <div class="col-md-12 stretch-card">
        <div class="card bg-transparent">
            <div class="card-body ">
                <h4 class="card-title fs-4">Formulaire de stock</h4>
                <hr>
                <form method="POST" action="{{ route('stocks.store') }}">
                    @csrf
                    <div id="form-container">
                       
                        <div class="form-section" data-index="0">
                            <div class="row" id="stock-form-container">
                            
                                <div class="col-sm-4">
                                    <div class="mb-3">
                                        <label class="form-label">choix D'article</label>
                                        <select  class="form-control" name="stocks[0][category]" id="categorie_stock">
                                            <!-- Options will be generated by JavaScript -->
                                        </select>
                                    </div>
                                </div><!-- Col -->
                            
                                <div class="col-sm-4">
                                    <div class="mb-3">
                                        <label class="form-label">Quantité</label>
                                        <input type="number" min="0" class="form-control" name="stocks[0][quantity]" value="" required>
                                    </div>
                                </div><!-- Col -->
                            
                                <div class="col-sm-4">
                                    <div class="mb-3">
                                        <label class="form-label">Prix</label>
                                        <input type="text" class="form-control" name="stocks[0][price]" placeholder="Entrez le prix" required>
                                    </div>
                                </div><!-- Col -->
                            </div>

                            <hr>
                        </div>
                        
                    </div>

                    <div> <button type="button" class="btn btn-secondary" id="add-more"><i class="link-icon" data-feather="plus-circle"></i> Ajouter autre élément</button>
                        <button type="button" class="btn btn-danger remove-section" id="remove-last">Supprimer le dernier article</button>
    </div>
                    
                   

                    <button type="submit" class="btn btn-primary col-sm-3 mt-3">Soumettre le Formulaire</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
let stockIndex = 1;

document.getElementById('add-more').addEventListener('click', function() {
    let formContainer = document.getElementById('form-container');
    let newFormSection = document.querySelector('.form-section').cloneNode(true);

    // Update names of the input fields
    newFormSection.querySelectorAll('input, select, textarea').forEach((input) => {
        let name = input.getAttribute('name');
        if (name) {
            input.setAttribute('name', name.replace(/\[\d+\]/, `[${stockIndex}]`));
            input.value = '';  // Reset the value
        }
    });

    // Add index attribute
    newFormSection.setAttribute('data-index', stockIndex);
    formContainer.appendChild(newFormSection);

    stockIndex++;

    // Show the remove button after the first form is added
    document.getElementById('remove-last').style.display = 'inline-block';
});


// Array of car material categories
// Object of car material categories grouped by section
const groupedCategories = {
    "Fluides et Lubrifiants": [
        { value: "huile", text: "Huile" },
        { value: "liquide_de_frein", text: "Liquide de Frein" },
        { value: "additifs", text: "Additifs" }
    ],
    "Éléments de Sécurité": [
        { value: "pneus", text: "Pneus" },
        { value: "essuie_glaces", text: "Essuie-glaces" },
        { value: "ampoules", text: "Ampoules" }
    ],
    "Filtres et Bougies": [
        { value: "filtre_a_air", text: "Filtre à Air" },
        { value: "filtres_a_huile", text: "Filtres à Huile" },
        { value: "filtres_a_carburant", text: "Filtres à Carburant" },
        { value: "bougies", text: "Bougies" },
        { value: "bougies_de_prechauffage", text: "Bougies de Préchauffage" }
    ],
    "Composants de Freinage": [
        { value: "plaquettes_de_frein", text: "Plaquettes de Frein" },
        { value: "disques_de_frein", text: "Disques de Frein" }
    ],
    "Composants Mécaniques": [
        { value: "alternateur", text: "Alternateur" },
        { value: "pompe_a_eau", text: "Pompe à Eau" },
        { value: "pompe_a_essence", text: "Pompe à Essence" },
        { value: "embrayage", text: "Embrayage" },
        { value: "boite_de_vitesse", text: "Boîte de Vitesse" },
        { value: "echappement", text: "Échappement" }
    ],
    "Composants Électriques": [
        { value: "batterie", text: "Batterie" },
        { value: "alternateur", text: "Alternateur" }  // Alternator can be considered here too if needed
    ],
    "Autres Composants": [
        { value: "radiateur", text: "Radiateur" },
        { value: "volant_moteur", text: "Volant Moteur" },
        { value: "verins_de_haillon", text: "Vérins de Haillon" },
        { value: "rotules_de_direction", text: "Rotules de Direction" },
        { value: "amortisseurs", text: "Amortisseurs" },
        { value: "silent_blocs", text: "Silent-blocs" },
        { value: "cardans", text: "Cardans" },
        { value: "roulements", text: "Roulements" },
        { value: "reservoir_a_carburant", text: "Réservoir à Carburant" }
    ],
    "Autre": [
        { value: "autre", text: "Autre" }
    ]
};


// Function to populate categories
function populateCategories() {
    const categorieStockSelect = document.getElementById('categorie_stock');

    for (const [groupName, categories] of Object.entries(groupedCategories)) {
        let optgroup = document.createElement('optgroup');
        optgroup.label = groupName;

        categories.forEach(category => {
            let option = document.createElement('option');
            option.value = category.value;
            option.textContent = category.text;
            option.style.backgroundColor = "";
            optgroup.appendChild(option);
        });

        categorieStockSelect.appendChild(optgroup);
    }
}

// Function to add a new stock form
function addStockForm() {
    const formContainer = document.getElementById('stock-form-container');
    const formIndex = document.querySelectorAll('#stock-form-container .row').length;

    // Clone the first form and update the names
    const newForm = formContainer.cloneNode(true);
    newForm.querySelectorAll('input, select').forEach(input => {
        input.name = input.name.replace(/\[\d+\]/, `[${formIndex}]`);
        input.value = '';
    });

    // Append the new form
    document.getElementById('stock-form-container').appendChild(newForm);
}

// Initialize categories when the page loads
document.addEventListener('DOMContentLoaded', populateCategories);



document.getElementById('remove-last').addEventListener('click', function() {
    let formContainer = document.getElementById('form-container');
    if (stockIndex > 1) {
        stockIndex--;
        let lastForm = formContainer.querySelector(`.form-section[data-index="${stockIndex}"]`);
        lastForm.remove();

        // Hide the remove button if only the principal form is left
        if (stockIndex === 1) {
            document.getElementById('remove-last').style.display = 'none';
        }
    }
});
</script>

@endsection
